apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cart
    spec:
      containers:
      - name: cart
        image: reactivesw/cart:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: server_port
          value: "80"
        - name: spring_datasource_url
          value: jdbc:postgresql://pg-data/cart
        - name: spring_cloud_config_uri
          value: http://reactivesw-config