server:
  port: 8081

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


product:
  service:
    uri: http://35.184.19.183/products/
customer:
  service:
    uri: http://localhost:8084/

io:
  reactivesw:
    message:
      broker:
        host: http://umasuo.com
      brokerType: google
      google:
        project:
          id: reactivesw-project
