server:
  port: 8081

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update


product:
  service:
    uri: http://product/
customer:
  service:
    uri: http://localhost:8084/

io:
  reactivesw:
    message:
      broker:
        host: http://www.reactivesw.org
      brokerType: google
      topic:
        signin:
          name: reactivesw-dev-customer-login
          version: 1
          subscriber: dev-customer-cart-merge
      google:
        project:
          id: reactivesw-project
